import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/config/fonts";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-gradient-to-r from-primary to-purple-950  text-secondary`}>
        <main className="flex min-h-screen max-w-7xl flex-col items-center justify-between p-24 mx-auto">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
